### ISSUE TITLE
Player Turns

### ISSUE THREAD

**Issue by dilarakkl** [kadron/splendor-prolog#10]
I noticed something odd about the gameplay. It seems like it gives some players consecutive turns. 
Log-->
I am player1 of a 2 player game.
I am player2 of a 2 player game.
Step 1: player1 chooses action: reserveCard(205) 
player1 chooses action: getGems([0,1,0,1,1,0],[0,0,0,0,0,0]) 
Step 2: player2 chooses action: getGems([0,1,1,0,1,0],[0,0,0,0,0,0]) 
Step 3: player1 chooses action: getGems([0,1,1,0,1,0],[0,0,0,0,0,0]) 
Step 4: player2 chooses action: getGems([1,1,1,0,0,0],[0,0,0,0,0,0]) 
Step 5: player1 chooses action: getGems([0,0,1,1,1,0],[0,0,0,0,0,0]) 
Step 6: player2 chooses action: getGems([1,0,0,1,0,0],[0,0,0,0,0,0]) 
Step 7: player1 chooses action: getGems([1,0,0,1,0,0],[0,0,0,1,0,0]) 
Step 8: player2 chooses action: reserveCard(11) 
player2 chooses action: buyCard(11)

**Comment by basarane** [comment]
it's weird. I'll check it. Are both players randomPlayer?

**Comment by basarane** [comment]
This problem is probably related with #11 Since the second action is only performed after reserveCard action. `reserveCard` action in randomPlayer fails since there need to be an extra parameter. Since it fails, it backtracks and tries a second action. 

See #11  for details.
