### ISSUE TITLE
ReserveCard fails.

### ISSUE THREAD

**Issue by ilhanadiyaman** [kadron/splendor-prolog#11]
When I try to reserve a card by using reserveCard(_) predicate, it always fails.

?- runGame([human, randomPlayer]).
I am player1 of a 2 player game.
I am player2 of a 2 player game.
Step 1: 
GAME STATE
cards: [27,37,16,40,120,104,118,110,216,212,201,217]
nobles: [507-[4,0,0,0,4,0]-3,501-[3,3,0,0,3,0]-3,503-[3,0,0,3,3,0]-3]
tokens: [4,4,4,4,4,5]

OPONENT STATE
bonuses: [0,0,0,0,0,0]
gems: [0,0,0,0,0,0]
module: randomPlayer
nobleTiles: []
reserves: []
score: 0

YOUR STATE
bonuses: [0,0,0,0,0,0]
gems: [0,0,0,0,0,0]
module: human
nobleTiles: []
reserves: []
score: 0
'your action: 'reserveCard(216).
player1 chooses action: reserveCard(216) 
false.

You can see this issue on randomPlayer agents as well. According to code, random players are always reserving cards if available. However, they act as purchase oriented agent. But somehow, in some turns, they achieve reserving cards.

**Comment by basarane** [comment]
The parameters of reserveCard predicate is changed. There is an extra parameter `BackGems`, which is a list of length 6. 

```
reserveCard(CardId, BackGems)
```

Normally you pass [0,0,0,0,0,0] for most of the times. However if the player will have 11 gems after reserving card, it must give one gem back. In this case, the list should have exactly one 1. 

`reserveCardFromDeck` predicate also has `BackGems` parameter. 

```
reserveCardFromDeck(DeckId, BackGems)
```

Feel free to update randomPlayer to reflect these changes.
