### ISSUE TITLE
Each agent should play equal number of times before termination

### ISSUE THREAD

**Issue by mrtysn** [kadron/splendor-prolog#14]
runOneIteration should be called nPlayer times in runOneRound to ensure equal rounds for each player.

**Comment by basarane** [comment]
The following last line of `doAction(Action)` predicate increments the turn 

```
nextTurn
```

If the action is successfull, the turn is incremented and on the next run of `runOneIteration` next player is asked to perform the action. 

The end of the game is checked by `isGameEnded` predicate which is called before the action performed by the next player. It only succeeds when the first player has the turn and there exists at least one player with score >= 15.

Hope this info helps.
