### ISSUE TITLE
Frame gets multiple valid actions

### ISSUE THREAD

**Issue by yasinalm** [kadron/splendor-prolog#23]
the frame code accepts multiple valid actions. When the code comes to

```
Module:decideAction(Player, Oponents, stateProxy, Action)
```

this may cause a branch and prolog backtraces the other valid moves. This may allow tricky moves. I am not sure whether it affects the final result or not. Here is a log of a game between two randomPlayer

```
runGame([randomPlayer, randomPlayer]).
```

The log where we can see the problem:

```
Step 31: player1 chooses action: reserveCard(201) 
player1 chooses action: buyCard(19) 
Available cards:19 [] [37,19,16,4,106,101,108,118,209,213,201,217]
Getted noble tiles: []
Step 32: player2 chooses action: reserveCard(16) 
player2 chooses action: getGems([1,0,1,1,0,0],[0,0,0,0,0,0]) 
```

I tried fixing it with a simple cut after decideAction but it didn't work.

**Comment by basarane** [comment]
This is related with the other issues #10 and #11. The problem was with `randomPlayer` code. A new parameter was added to `reserveCard` and `reserveCardFromDeck` actions in frame code. With update 1e57ecd `randomPlayer` code is fixed.
