### ISSUE TITLE
Winner Declaration

### ISSUE THREAD

**Issue by dilarakkl** [kadron/splendor-prolog#25]
Can we add some kind of a stateProxy that will announce the end of game with the winner to the agents so we can add learning?

**Comment by basarane** [comment]
I updated the githup repo. Please check if this resolves the issue.

**Comment by basarane** [comment]
a86cf6a resolves the issue

**Comment by dilara91** [comment]
Hi! I tried the code buy predicate_property(PlayerModule:onGameEnd(_,_,_), static) gives false when it is supposed to give true. I tried this on randomPlayer also this is the case for it too.
