### ISSUE TITLE
onGameEnd

### ISSUE THREAD

**Issue by dilarakkl** [kadron/splendor-prolog#26]
predicate_property(randomPlayer:onGameEnd(_,_,_),static).

does not work. However if we make the static as interpreted I think it will work.

**Comment by basarane** [comment]
it works on my Windows 7 machine with SWI-Prolog version 7.2.3.

**Comment by basarane** [comment]
I also updated the next line with the type 'interpreted' as follows

```
 \+ predicate_property(PlayerModule:onGameEnd(_,_,_), interpreted)
```
