### ISSUE TITLE
is gems valid

### ISSUE THREAD

**Issue by dilarakkl** [kadron/splendor-prolog#3]
In the methods checking for validity of gems, isGemValid4 has some problems I think. In the line 619 they have M <=1 and then they give the case M=2 ok in the line 623 and this code will not be reached in any case. Also isnt it ok to get 2 different gems in case there are only 2 piles of tokens even if one of the piles is at least size 4.

**Comment by basarane** [comment]
You are right, that line never succeeds. However the first part (M>1,B=1) is already satisfied for M=2.

I recheck the game, it does not allow you to get one from each color if one pile is at least size 4. However the project specs states the opposite. Let's @kadron decide that.

**Comment by kadron** [comment]
The official implementation doesn't let it but game designers from Asmodee (publisher of this game) state that is should be possible to pick 2 coins when there is a pile with 4 coins. I think we should make this possible in our implementation as well.
[Link to designer's answer](https://boardgamegeek.com/article/15431700#15431700)

**Comment by basarane** [comment]
I update `isGetGemValid4` predicate to reflect this change. Also update 'tests.pl' file.
